package com.omnicrola.voxel.ui;

/**
 * Created by Eric on 1/24/2016.
 */
public enum UiToken implements IUiToken {
    BUTTON_START,
    BUTTON_MULTIPLAYER,
    BUTTON_QUIT_GAME,
    SELECTION_PANEL,
    TEAM_RESULTS_PANEL,
    ACTION_1,
    ACTION_2,
    ACTION_3,
    ACTION_4,
    ACTION_5,
    ACTION_6,
    ACTION_7,
    ACTION_8,
    ACTION_9,
    ELAPSED_TIME,
    BUTTON_MAIN_MENU,
    TEAM_RESULTS_CONTAINER,
    RESOURCE_AMOUNT,
    BUTTON_ABORT_SERVER_CONNECT,
    BUTTON_START_MULTIPLAYER;

}
